### ISSUE TITLE
jaccard's function

### ISSUE THREAD

**Issue by elgabbas** [cbig/zonator#64]
Hello,

It seems that there is an error with implementing `jaccard`'s function. It always gives a similarity value of 1

Example:
```
require(zonator)
require(raster)
R1 <- raster(matrix(data = sample(x = c(0,1), size = 100, replace = T), nrow = 10, ncol = 10))
R2 <- raster(matrix(data = sample(x = c(0,1), size = 100, replace = T), nrow = 10, ncol = 10))
jaccard(R1,R2)
```

The error seems to be in line numbers 214-215
```
x.bin <- (x >= x.min & x <=x.max)
y.bin <- (y >= y.min & y <=y.max)
```

Cheers,
Ahmed

**Comment by jlehtoma** [comment]
Since you're not defining `x.max`, `x.min`, `y.max` or `y.min`, the defaults are used (1.0, 0.0, 1.0 and 0.0 respectively). This means that all cells in both of your rasters are evaluated (lines 214-215) as `TRUE` and hence the Jaccard coefficient is 1.0. There is no error here, `jaccard` just isn't smart enough to understand that you're feeding in binary rasters. You can get the correct value by setting `x.min` and `y.min` to anything > 0, e.g.

```
jaccard(R1,R2, x.min = 0.1, y.min = 0.1)
```
