### ISSUE TITLE
'--no-staged-install' error on installation

### ISSUE THREAD

**Issue by heislele** [cbig/zonator#68]
Hi there! 

I ran into an error when installing zonator: '--no-staged-install'. I was asked to report and was hoping you could help me resolve?

I'm new to github so if there is any information you need from me please let me know.

**Comment by jlehtoma** [comment]
Hi @heislele, thanks for reporting this and sorry taking a little time to respond!

`zonator` currently relies on [disabling staged install](https://developer.r-project.org/Blog/public/2019/02/14/staged-install/) which is a feature added in R version 3.6. Which version of R you're using? If older than 3.6, then updating might solve the issue. 

In the longer run, I plan to update `zonator` so that staged installation doesn't need to be disabled, but this will take a bit longer time.

**Comment by heislele** [comment]
I'll try updating R, thanks for your help @jlehtoma !

**Comment by jlehtoma** [comment]
Version 0.6.0 no longer depends on --no-staged-install so closing this issue.
